### ISSUE TITLE
Responsive display improvements

### ISSUE THREAD

**Issue by vaab** [Lokavaluto/lokavaluto-web-application#10]
When displaying website on computer display and on mobile site, here are suggestions:

- The 3 buttons stay horizontally stacked, this leads to broken display and button labels being half displayed and unusable.
- Their is a large white block underneath the page that seems useless
- Blocks (transactions) is clipped and not usable

The bottom buttons are not visible by default, can't they stay on the bottom and be fixed ?
Can't the Blocks ("Solde General", "Vos Comptes") be stacked vertically when used on a 
narrow display (like a phone ?).

Full actions and modal should be tested for correct behavior on mobile screen form factor.

**Comment by MatSarr** [comment]
@stephansainleger said that it was a made decision not to offer a responsive web app. 

Instead, in V1 we should add a feature which redirect to the mobile app if opening the web app on mobile

**Comment by vaab** [comment]
To my opinion, making a responsive app is easy and quick (especially with such easy layouts), and all website nowadays should be responsive.
Responsive is not about mobile only, it is to have a sane layout, that could work on a tablet, on a computer in a smaller window. Plus, I might want to access the website with my phone without wanting to install an app (for a one-of, or because I have too many apps installed on my phone, or because it slows my phone, or I don't like the permissions taken by the app).
The web app design is totally made for mobile app with very large buttons menu, some elements are already responsible, it seems just not finished.
It seems strange here, to me, not to simply support mobile layout as a basic requirement.
