### ISSUE TITLE
Display all accounts in 'Your Accounts'

### ISSUE THREAD

**Issue by vaab** [Lokavaluto/lokavaluto-web-application#22]
We are actually not displaying all the accounts given by lokapi `.getAccounts()` in `YourAccs.vue`.
That would be nice.

**Comment by seegwen** [comment]
Should be fixed in PR #24

**Comment by seegwen** [comment]
#24 is closed as wontapply, should be fixed in #31

**Comment by vaab** [comment]
thx for heads up
